// Lista de países (nomes em Português de Portugal) para o campo "País de destino".
// Os mercados mais frequentes ficam no topo; o resto segue por ordem alfabética.

export const PAISES: string[] = [
  // Mais frequentes
  'Portugal',
  'Espanha',
  'França',
  'Itália',
  'Alemanha',
  'Reino Unido',
  'Bélgica',
  'Países Baixos',
  'Suíça',
  'Luxemburgo',
  'Irlanda',
  'Áustria',
  // Resto da Europa
  'Andorra',
  'Albânia',
  'Bielorrússia',
  'Bósnia e Herzegovina',
  'Bulgária',
  'Chéquia',
  'Chipre',
  'Croácia',
  'Dinamarca',
  'Eslováquia',
  'Eslovénia',
  'Estónia',
  'Finlândia',
  'Grécia',
  'Hungria',
  'Islândia',
  'Letónia',
  'Listenstaine',
  'Lituânia',
  'Macedónia do Norte',
  'Malta',
  'Moldávia',
  'Mónaco',
  'Montenegro',
  'Noruega',
  'Polónia',
  'Roménia',
  'Sérvia',
  'Suécia',
  'Ucrânia',
  'Vaticano',
  // Países lusófonos / mercados habituais
  'Angola',
  'Brasil',
  'Cabo Verde',
  'Guiné-Bissau',
  'Moçambique',
  'São Tomé e Príncipe',
  'Timor-Leste',
  // Médio Oriente / África / Ásia / Américas frequentes
  'África do Sul',
  'Arábia Saudita',
  'Argentina',
  'Austrália',
  'Canadá',
  'Catar',
  'Chile',
  'China',
  'Colômbia',
  'Coreia do Sul',
  'Egito',
  'Emirados Árabes Unidos',
  'Estados Unidos',
  'Índia',
  'Indonésia',
  'Israel',
  'Japão',
  'Kuwait',
  'Marrocos',
  'México',
  'Nova Zelândia',
  'Singapura',
  'Tunísia',
  'Turquia',
]
