insert into public.tabela_precos (nome, categoria, referencia, preco, ativo) values
('Accent Prime', null, 'ACCENTPR', 0.0, true),
('Accent Ultra', null, 'ACCENTUL', 0.0, true),
('Accessories For Soprano Ice', null, 'AccessSop', 0.0, true),
('Accessories', null, 'ACCS', 0.0, true),
('Accessories', null, 'ACES', 0.0, true),
('Acessórios Automóvel', null, 'AcessAuto', 0.0, true),
('AC - Line Filter', null, 'ACLF', 0.0, true),
('Acupulse', null, 'Acu', 0.0, true),
('Adaptador', null, 'ADAP', 0.0, true),
('Adaptador ZImmer Gpro', null, 'Adaptador Zimmer', 0.0, true),
('Advance', null, 'Adv', 0.0, true),
('Advanced Payment', null, 'Adv. P', 0.0, true),
('Acessorio de equipamento de beleza', null, 'AEB', 0.0, true),
('Acessorio Equipamento de Estetica', null, 'AEE', 0.0, true),
('Aesclepium', null, 'AESc', 0.0, true),
('Aiming beam', null, 'AimingB', 0.0, true),
('Airclips', null, 'AirC', 0.0, true),
('Air Filter MGL/MGY Chassis', null, 'AIRFILT', 0.0, true),
('Alma', null, 'Al', 0.0, true),
('Aluguer Radiofrequência Apollo', null, 'AL_APOLLO', 0.0, true),
('Aluguer Formatk', null, 'AL_FORMA', 150.0, true),
('Aluguer Laser', null, 'AL_LASER', 0.0, true),
('Accessories for Accent Ultra 230V', null, 'ALACSS', 0.0, true),
('Accent Ultra System 230V', null, 'ALAUV', 0.0, true),
('Pagamento por conta de aluguer de equipamentos no período de 15 de Outubro 2013 a 31 de Maio 2014', null, 'ALEQUIPBB', 0.0, true),
('Alex', null, 'Alex', 0.0, true),
('Alma Lasers Doiode Handpiece', null, 'Alma Lasers Doi', 0.0, true),
('Alma Packed System', null, 'ALMA Pack', 0.0, true),
('Alma Lasers', null, 'ALMALASERS', 0.0, true),
('Alquiler', null, 'Alquiler', 0.0, true),
('Alma Laser - Soprano XLI', null, 'ALS', 0.0, true),
('Aluguer Endymed', null, 'ALU_ENDY', 0.0, true),
('UltraBody Handpiece', null, 'ALUBHP', 0.0, true),
('UltraFace Handpiece', null, 'ALUFHP', 0.0, true),
('Aluguer', null, 'Alug', 0.0, true),
('Aluminum bottle for filling gasses', null, 'ALUMBOTTLE', 0.0, true),
('Uniface Handpiece', null, 'ALUNIBH', 0.0, true),
('UniBody Handpiece', null, 'ALUNIH', 0.0, true),
('Aluguer Mimi GentleLase', null, 'AMGL', 0.0, true),
('Acordo de Pagamento de Divida datado 3 de Março 2014', null, 'APD', 0.0, true),
('Apoio Lateral Candela', null, 'APLAT', 0.0, true),
('Applique', null, 'App', 0.0, true),
('Water Pump, Power supply,Hitter Capacitor', null, 'Aquarium Parts', 0.0, true),
('Antenna Standalone Assy For Soprano Ice & XLi Black (Service)', null, 'ASASoprano', 0.0, true),
('Assistência Técnica', null, 'Assist', 0.0, true),
('Audio amplifier', null, 'AUDIO', 0.0, true),
('Avaria', null, 'Avar', 0.0, true),
('Alexandrite window', null, 'AW', 0.0, true),
('Parceria Formatk Manipulo B-HR', null, 'B-HR', 0.07, true),
('Nib da Empresa para pagamento da factura: 0010 0000 4101 165000165', null, 'Banco BPI', 0.0, true),
('Bank', null, 'Bank', 0.0, true),
('BANK NAME-BAnco BPI SA  BANK ADDRESS-Rua Tenente Valadim  CONTACT:2844100476', null, 'BankAddress', 0.0, true),
('Barium Powder', null, 'BARIUM', 0.0, true),
('Beam', null, 'Beam', 0.0, true),
('Beauty', null, 'Beau', 0.0, true),
('Beautification Apparatus', null, 'BeauAp', 0.0, true),
('Bezel', null, 'Bez', 0.0, true),
('Bipolar Thermometer Handpiece', null, 'BITH', 0.0, true),
('Board', null, 'Board', 0.0, true),
('Boards for cryogen', null, 'Boardcryo', 0.0, true),
('Bobine do sistema de capacitação', null, 'BOB', 0.0, true),
('Bomba', null, 'Bomba', 0.0, true),
('Bottles', null, 'Bot', 0.0, true),
('Broken', null, 'Brok', 0.0, true),
('BTL', null, 'BTL', 0.0, true),
('Candela Pro Series Button - For Handpiece', null, 'BUTT', 0.0, true),
('Bleeder Voltage Board', null, 'BVoltageboard', 0.0, true),
('Cabeça', null, 'Cab', 0.0, true),
('Cabeça Laser Alexandrite', null, 'CABLASALEX', 0.0, true),
('Cables Kit', null, 'Cables', 0.0, true),
('Cabezal', null, 'Cabz', 0.0, true),
('Calport', null, 'CAL', 0.0, true),
('MGL Calport Ceramic', null, 'CALPORT_CERAMIC', 0.0, true),
('MGL Calport Lens', null, 'CALPORT_LENS', 0.0, true),
('Calport Window', null, 'CalpWindow', 0.0, true),
('Candela Cooling Partes', null, 'CandelaCooling', 0.0, true),
('Candela Gmax', null, 'CandGmax', 0.0, true),
('Canhão', null, 'Canh', 0.0, false),
('Canister', null, 'Canister', 0.0, true),
('Cap', null, 'CAP', 0.0, true),
('Cap and Level Sensor', null, 'CAP_LEV', 0.0, true),
('Capacitor Mini GentleLase Alexandrite', null, 'CAPACITOR', 0.0, true),
('Capas', null, 'Capas', 0.0, true),
('Capacitor Charger', null, 'CapCharge', 0.0, true),
('Carcaza', null, 'Carc', 0.0, true),
('Transducer card', null, 'Card', 0.0, true),
('Carga Azoto/Teste de fugas', null, 'CARGA ZIMMER', 0.0, true),
('Carga de Fluido refrigerante R404A', null, 'CARGAFLUIDO', 0.0, true),
('Cartuxos', null, 'CART', 0.0, true),
('GentleLASE/GentleYAG DI Cartridge for DI Fluid System', null, 'CARTDR', 0.0, true),
('Metal Case', null, 'Case', 0.0, true),
('Cavity Bock', null, 'CAV', 0.0, true),
('Cavitação Beauty Services', null, 'CAVBS', 0.0, true),
('Control Board', null, 'CBoard', 0.0, true),
('Candela Unit', null, 'CDL', 0.0, true),
('Cynosure Elite Fiber', null, 'CEF', 0.0, true),
('Cynosure Elite Laser', null, 'CEL', 0.0, true),
('Spare Part', null, 'Chassis', 0.0, true),
('Chip', null, 'Chip', 0.0, true),
('CIF aguarda aprovacion del VIES.', null, 'CIF', 0.0, true),
('Circuit', null, 'Cir', 0.0, true),
('Complete Laser Chamber', null, 'CLC', 0.0, true),
('ClearLift 1064/532nm KTP with Pixel', null, 'CLEARL', 0.0, true),
('Clearlift', null, 'CLEARLIFT', 0.0, true),
('ClearSkin 1540 - Erbium CoolGlass With Vacuum 1540 nm', null, 'CLEARSK', 0.0, true),
('Clearlift Tips', null, 'CLEARTIPS', 0.0, true),
('Clinical and Technical Training: Diferences Between Lasers Alexandrite and Diode', null, 'CLETC_TR', 0.0, true),
('Clinical Training - Harmony XL', null, 'CLIN_TR', 0.0, true),
('Clinical Training: Laser Alexandrite', null, 'CLINIC_TR', 0.0, true),
('Controle Module System', null, 'CMS', 0.0, true),
('Cabaz de Natal', null, 'CNatal', 0.0, true),
('CO2', null, 'CO2', 0.0, true),
('CO2 Fracionado', null, 'CO2F', 0.0, true),
('Cocoon', null, 'Coc', 0.0, true),
('Cópia Chave', null, 'COCHA', 0.0, true),
('Harmonized code 8543709099', null, 'CODHARM', 0.0, true),
('Coils', null, 'COILS', 0.0, true),
('Collection costs', null, 'COLCOSTS', 0.0, true),
('Comissão de venda de equipamentos', null, 'COM', 0.0, true),
('Compressor', null, 'COMP', 0.0, true),
('Contactor', null, 'CON', 0.0, true),
('Condensadores', null, 'Cond.', 0.0, true),
('Connectors for Water Tank - Small One', null, 'CONNWT_S', 0.0, true),
('Consignee', null, 'CONS', 0.0, true),
('Yag Lenses', null, 'CONS_YAG', 0.0, true),
('Criogenio', 'Consumíveis', 'CONS01', 55.0, false),
('Pack 50 Lentes GentleLaseAlex + 35 Oferta', 'Consumíveis', 'CONS02', 350.0, true),
('Pack 100 Lentes GentlelaseAlex + 80 Oferta', 'Consumíveis', 'CONS03', 650.0, true),
('Distanciadores Transparentes 18mm', 'Consumíveis', 'CONS04', 69.0, true),
('Pack 50 Lentes GentleLaseYag + 20 Oferta', 'Consumíveis', 'CONS05', 350.0, true),
('Distanciadores Transparentes 15mm', 'Consumíveis', 'CONS06', 0.0, true),
('Distanciadores Transparentes 12mm', 'Consumíveis', 'CONS07', 0.0, true),
('Fibra Óptica Mini GentleLase', 'Consumíveis', 'CONS08', 0.0, true),
('Pack 25 Lentes GentleLase Alex', 'Consumíveis', 'CONS09', 150.0, true),
('Lente GentleLase Alex', 'Consumíveis', 'CONS10', 0.0, true),
('Transdutor Ultrashape', 'Consumíveis', 'CONS11', 0.0, true),
('Complemento de Transdutor', 'Consumíveis', 'CONS12', 972.0, true),
('KIT DE TRATAMENTO ULTRASHAPE', null, 'CONS13', 20.0, true),
('Fibra Optica Mini Gentle Yag', 'Consumíveis', 'CONS14', 2000.0, true),
('12 Garrafas Criogénio -3 Oferta', null, 'CONS15', 480.0, true),
('24 Garrafas de Criogénio - Oferta 9', null, 'CONS16', 960.0, true),
('Castor Oil - Ultrasonic Coupling Fluid - 80cc', null, 'CONS17', 0.0, true),
('IPL - PEÇA DE MÃO', null, 'CONS18', 3000.0, true),
('Cabeças de Transdutores Ultrashape Usados', 'Peças', 'CONS19', 0.0, true),
('Cadeado 34mm', 'Consumíveis', 'CONS20', 2.9, true),
('Garrafas de Água para Desporto c/ logo', null, 'CONS21', 3.3, true),
('Mochila de Cordão para Desporto c/logo', null, 'CONS22', 1.64, true),
('Toalha 100% algodão 450 grm 70*140 c/ logo', null, 'CONS23', 2.95, true),
('Trigger Button MGL', 'Manutenção e Reparação', 'CONS24', 225.0, true),
('High Voltage Power Supply HVPS', null, 'CONS25', 0.0, true),
('Glass for Alexandrite', null, 'CONS26', 0.0, true),
('Laser Head Case', null, 'CONS27', 0.0, true),
('Slider for Mini GentleLase Plus', null, 'CONS28', 0.0, true),
('Flashlamp DEKA SmartEpil', 'Consumíveis', 'CONSDEKA01', 1000.0, true),
('Conserto', null, 'CONSE', 0.0, true),
('CONSIGNAÇÃO: Exportação temporária / Consignment – No transfer of ownership', null, 'CONSG', 0.0, true),
('Serviços de consultoria', null, 'CONSINT', 0.0, true),
('Contract nº', null, 'CONT', 0.0, true),
('Control panel parts', null, 'ControlPP', 0.0, true),
('Connectors for Water Tank - Big one', null, 'CONWT_B', 0.0, true),
('Cooling', null, 'Coo', 0.0, true),
('Cooler Part', null, 'CoolerPart', 0.0, true),
('Cooltech', null, 'Coolt', 0.0, true),
('CO2RE', null, 'Core', 0.0, true),
('Country of Origin:', null, 'CORIGIN', 0.0, true),
('Condições de pagamento', null, 'CPAG', 0.0, true),
('Cynosure Packed System', null, 'CPS', 0.0, true),
('Ceramic Plate Sample', null, 'CPSample', 0.0, true),
('CPU', null, 'Cpu', 0.0, true),
('Crating', null, 'Crat', 0.0, true),
('Crystal', null, 'CRi', 0.0, true),
('CRIOGEN ADAPTER', null, 'CRIOADPT', 0.0, true),
('Criogen Cap', null, 'CrioCap', 0.0, true),
('Criogen Valve', null, 'CrioVal', 0.0, true),
('Cristal', null, 'Cristal', 0.0, true),
('Crate', null, 'CRT', 0.0, true),
('Cryogen', null, 'Cryo', 0.0, true),
('CRYO 5', null, 'CRYO5', 0.0, true),
('CRYO 6', null, 'CRYO6', 0.0, true),
('Cryo Cannisters', null, 'CRYOCAN', 0.0, true),
('Criogénio tampa', null, 'CRYOCAP', 0.0, true),
('Cryogen Valve', null, 'CRYOV', 0.0, true),
('Cryo Zimmer 5', null, 'CRYOZ5', 0.0, true),
('Contrato Manutenção Simples - Mensalidade', 'Contratos Manutenção', 'CSIMPL', 250.0, true),
('CYNOSURE SMOTHSHAPES', null, 'CSS', 0.0, true),
('Contrato Manutenção Standard - Mensalidade', 'Contratos Manutenção', 'CSTAND', 416.7, true),
('Custos Envio', null, 'CustE', 0.0, true),
('Cutera', null, 'CUT', 0.0, true),
('Cutera Xeo', null, 'CUT_XEO', 0.0, true),
('Cutera enlighten', null, 'CUTERA', 0.0, true),
('Caixa', null, 'CX', 0.0, true),
('Caixa de Peça de Mão', null, 'CxPMão', 0.0, true),
('Cynosute Elite Plus', null, 'CYN_ELPLUS', 0.0, true),
('Cynosure Apogee', null, 'CYNAP', 0.0, true),
('Cynosure Cooling', null, 'CYNCoo', 0.0, true),
('Cynosure Elite', null, 'Cynoelite', 0.0, true),
('Cynosure Elite IQ', null, 'CynoEliteIQ', 0.0, true),
('Cynosure Elite Plus', null, 'Cynoeliteplus', 0.0, true),
('Cynosure Handpiece 3mm', null, 'Cynosure 3mm', 0.0, true),
('FACTURA  SEM PAGAMENTO PARA EFEITOS ADUANEIROS', null, 'DADOS', 0.0, true),
('Nº SERIE', null, 'DADOS 1', 0.0, true),
('BPI SA : Rua Tenente Valadim 284, 4100-476 Porto', null, 'Dados Banco', 0.0, true),
('DCD Heater', null, 'DCD', 0.0, true),
('DCD Nozzle', null, 'DCD Noz', 0.0, true),
('DCD HP Valve New', null, 'DCD_HP VALVE', 0.0, true),
('DELIVERY TERM:', null, 'DEL', 0.0, true),
('Delivery System', null, 'DEL_SYS', 0.0, true),
('Delivery address', null, 'DELADDRESS', 0.0, true),
('Immediately', null, 'Delivery Date', 0.0, true),
('Demonstração', null, 'DEMO', 0.0, true),
('Depósito', null, 'dep', 0.0, true),
('Descrição', null, 'des', 0.0, true),
('Desconto', null, 'DESC', 0.0, true),
('Descrição', null, 'Descrição', 0.0, false),
('Deslocação', null, 'DESLO', 0.0, true),
('Despesas Contractuais', 'Equipamentos', 'DESP01', 0.0, true),
('Detector', null, 'Detector', 0.0, true),
('Di Filter', null, 'DI F', 0.0, true),
('DI Water Pump - Magnetic Drive 220V Barbed Fittings', null, 'DI_WP', 0.0, true),
('Clinical Training: diagnosing hair and skin', null, 'DIAG_TR', 0.0, true),
('DIMENSIONS:', null, 'DIM', 0.0, true),
('Diode Laser', null, 'Diolase', 0.0, true),
('Dirección de entrega', null, 'Direc', 0.0, true),
('Displacement', null, 'Dis', 0.0, true),
('Discount', null, 'DISC', 0.0, true),
('Display Case', null, 'DisCase', 0.0, true),
('Disco Rigido Ultrashape', null, 'DISCOUS', 0.0, true),
('Distance Gauce', null, 'DIST', 0.0, true),
('Distanciador Cynosure', null, 'Distanciador Cy', 0.0, true),
('Caixa de 5 distanciadores', null, 'DISTCAIXA', 0.0, true),
('5-Pack 15mm Amber Distance Gauge - 755nm Alex for GentleLASE Family', null, 'DISTGAU_15MM', 0.0, true),
('5-Pack 18mm Amber Distance Gauge - 755nm Alex for GentleLASE Family', null, 'DISTGAU_18MM', 0.0, true),
('Distribution Board', null, 'Distribution Bo', 0.0, true),
('Acerto Contas', 'Manutenção e Reparação', 'DIV01', 0.0, true),
('Diode Module', null, 'Dmodule', 0.0, true),
('Documentos', null, 'Docs.', 0.0, true),
('Parceria Formatk Manipulo D-PEEL', 'Equipamentos', 'DPEEL', 0.98, true),
('Drenante Go!DIet', null, 'DREN', 2.5, true),
('Diode 3D Speed HP For Soprano Ice Edition', null, 'DSopIce', 0.0, true),
('Details: Equipment refurbished.', null, 'DTLS', 0.0, true),
('DuraLITE-MGL Fiber Optic Assembly 12/15/18mm Mini-GentleLASE   755nm Alex', null, 'DUALITE_FOA', 0.0, true),
('Dump', null, 'DUM', 0.0, true),
('Dubtape', null, 'DupTApe', 0.0, true),
('Dye-VL', null, 'DyeVL', 0.0, true),
('Ecografo', null, 'ECO', 0.0, true),
('Ecrã Pixel Co2', null, 'ECRÃPI', 0.0, true),
('Electric', null, 'EL', 0.0, true),
('Electric', null, 'Elec', 0.0, true),
('Electronic', null, 'Elect', 0.0, true),
('Eletroestimulação', 'Equipamentos', 'ELET', 0.0, true),
('Empty Box for Power Supply', null, 'EmptBOX', 0.0, true),
('Emergency Switch', null, 'EmSwitch', 0.0, true),
('Endcap', null, 'ENDC', 0.0, true),
('Endymed Pró', null, 'Endymed', 0.0, true),
('ENdymed Flyeres and Clinical Result Books', null, 'Endymed Flyers', 0.0, true),
('Endymed Fine Haandpiece', null, 'Endymed HP', 0.0, true),
('Endymed Motor', null, 'Endymoto', 0.0, true),
('Electric Power Supply', null, 'EPS', 0.0, true),
('Equipo', null, 'EQU', 0.0, true),
('Equipment', null, 'Equip', 0.0, true),
('Air  Matress, Motor 220V; 80 cm', 'Peças', 'EQUIP 07', 143.38, true),
('MINI GENTLELASE PLUS', 'Equipamentos', 'EQUIP01', 23000.0, true),
('ULTRASHAPE CONTOUR I versão II', 'Equipamentos', 'EQUIP02', 0.0, true),
('MINI GENTLELASE YAG', 'Equipamentos', 'EQUIP03', 45000.0, false),
('Endymed Pro', 'Equipamentos', 'EQUIP04', 20000.0, true),
('V-BEAM AESTHETICA', 'Equipamentos', 'EQUIP05', 57000.0, true),
('QUANTUM', 'Equipamentos', 'EQUIP06', 49000.0, true),
('Radio Frequencia Tripolar', null, 'EQUIP08', 40000.0, true),
('ULTRASHAPE CONTOUR I versão III', null, 'EQUIP09', 0.0, true),
('Mini Gentle Yag HR/SRT/VR', null, 'EQUIP10', 25000.0, true);
insert into public.tabela_precos (nome, categoria, referencia, preco, ativo) values
('Velasmooth', null, 'EQUIP11', 0.0, true),
('Equipamento estética usado', null, 'EQUIUS', 0.0, true),
('Eskimo', null, 'ESK', 0.0, true),
('Evaporador', null, 'Evap', 0.0, true),
('Electrical Wires', null, 'EW', 0.0, true),
('Eye Shield', null, 'Eye_ Shield', 0.0, true),
('MGL Eyewear', null, 'Eyewear', 0.0, true),
('International Freight / Customs', null, 'F011113', 0.0, true),
('Factura ref:', null, 'FAC', 0.0, true),
('Facial Tips', null, 'FACIALT', 0.0, true),
('Fan', null, 'FAN', 0.0, true),
('Fatos LPG', 'Consumíveis', 'FATOS_LPG', 15.0, true),
('Femilft', null, 'FEM', 0.0, true),
('Femilift', null, 'FemLift', 0.0, true),
('Finger Switch', null, 'FGSWIT', 0.0, true),
('Fiber', null, 'Fiber', 0.0, true),
('Fibra Cynosure Elite', null, 'FiberCynosure', 0.0, true),
('Fiber Tool for Assemblying', null, 'FiberTool', 52.0, true),
('Inverter Charger 3KW', null, 'FIBON', 0.0, true),
('Fiber Optic', null, 'FIBOP', 0.0, true),
('Fiber Pole', null, 'FIBPO', 0.0, true),
('Fibra', null, 'Fibra', 0.0, true),
('Fibra Cynosure', null, 'FibraCyno', 1200.0, true),
('Filtro', null, 'Fil', 0.0, true),
('Filtro de Água', null, 'FILAgua', 0.0, true),
('FilmLamp', null, 'FilmLamp', 0.0, true),
('Filtros MGL', null, 'Filt', 0.0, true),
('Filtro Agua Soprano', null, 'FILT_SOP', 0.0, true),
('Filter Coopler', null, 'FILTERCO', 0.0, true),
('Filters', null, 'Filters', 0.0, true),
('Fixing Fees', null, 'FIXFI', 0.0, true),
('Fixing', null, 'Fixing', 0.0, true),
('Candela Flashlamp Model: GProU/GmaxPro', null, 'FL_GPRO', 0.0, true),
('Flash Lamps', null, 'FLamps', 0.0, true),
('Flash', null, 'Flash', 0.0, true),
('Candela Flow Tubes', null, 'FLOWT', 0.0, true),
('Flow Tubes', null, 'Fltubes', 0.0, true),
('MGL Focusing Lens', null, 'FOC_LENS', 0.0, true),
('Focal Lenses', null, 'FOC_LENSES', 0.0, true),
('Focus Lens Set', null, 'FOCUS_LENS', 0.0, true),
('FOOT PEDAL', null, 'FOOT PEDAL', 0.0, true),
('Footswitch', null, 'Footswitch', 0.0, true),
('Fibra Optica', null, 'FOptica', 0.0, true),
('Formação', null, 'Forma', 250.0, true),
('FormaPartner', null, 'FormaPartner', 0.0, true),
('Formatk', 'Equipamentos', 'FORMATK', 0.0, true),
('Fotona', null, 'Fot', 0.0, true),
('Parceria Formatk Manipulo FSR', null, 'FSR', 0.25, true),
('Flashtubes', null, 'FTubes', 0.0, true),
('Full Delivery System', null, 'FullSystem', 0.0, true),
('Funnels', null, 'Fun', 0.0, true),
('Fusivel', null, 'Fuse', 0.0, true),
('Garantia', null, 'Garantia', 0.0, true),
('100-Pack Premium Grade Distance Gauge Windows with 25-Pack O-Rings - 755nm Alex', null, 'GAUGEW_10025', 0.0, true),
('100-Pack Premium Grade Distance Gauge Windows', null, 'GAUWIND_100', 0.0, true),
('Grupo electrónico do manipulo', null, 'GEM', 0.0, true),
('Mini-GentleLASE HandPiece', null, 'GENTLEL_HP', 0.0, true),
('Gentle Lase Plus', null, 'GENTLEPLUS', 0.0, true),
('GENTLELASE PRO', null, 'GENTLEPRO', 0.0, true),
('Mini GentleYAG', null, 'GentleYag', 0.0, true),
('Gentle Yag', null, 'GentYag', 0.0, true),
('GentleLase Alexandrite', null, 'Glase', 0.0, true),
('GLASE PRO-U W/DCD', null, 'GLASE PRO-U W/DCD', 0.0, true),
('Gentle Lase Windows', null, 'GLASEWIN', 0.0, true),
('Glasses', null, 'Glass', 0.0, true),
('Gentle Max Candela', null, 'GMAX', 0.0, true),
('Gentlemax Pro', null, 'Gmax Pro', 0.0, true),
('GentleMax Pro System w/ACC & Standard 1  year warranty', null, 'GMAX PRO W/ACC', 0.0, true),
('GentleMax Pro', 'Equipamentos', 'GMAXPRO', 0.0, false),
('Candela GentleMax Pro Plus', null, 'GMPP', 0.0, true),
('Goggles', null, 'Gog', 0.0, true),
('Laser Goggles', null, 'GOGGLES', 0.0, true),
('Googles', null, 'GOOGL', 0.0, true),
('Googles for Alexandrite', null, 'GooglAlexa', 0.0, true),
('Pack de nutrição Go&Start', null, 'GOSTART', 90.0, true),
('GROSS WEIGHT', null, 'GROSS', 0.0, true),
('Gás', null, 'GS', 0.0, true),
('Handpiece', null, 'HAND', 0.0, true),
('Handle', null, 'Handle', 0.0, true),
('MGL Handpiece Shell', null, 'Handpiece Shell', 0.0, true),
('Hand piece Speed', null, 'HandSpeed', 0.0, true),
('Acne - AFT 420-950nm', null, 'HARMACN', 0.0, true),
('Harmonized Code', null, 'HARMC_M', 0.0, true),
('Harmonized Code 90189084', null, 'HARMC_MED', 0.0, true),
('Harmony XL', null, 'HARMXL', 0.0, true),
('Nd:YAG/HP Nd:YAG 1064nm', null, 'HARNDYAG', 0.0, true),
('HS CODE', null, 'HC', 0.0, true),
('Head Cover', null, 'HCover', 0.0, true),
('Head', null, 'Head', 0.0, true),
('MGL Heater Assembly', null, 'Heater Assembly', 0.0, true),
('Heater', null, 'Heater Simple', 400.0, true),
('Hose', null, 'Hose', 0.0, true),
('Handpiece cable DCD', null, 'HPCable DCD', 0.0, true),
('HP control PCB', null, 'HPControl', 0.0, true),
('HP End Cap Lems Set', null, 'HPEND', 0.0, true),
('Handpiece for repair', null, 'HPFR', 0.0, true),
('ET-Head piece', null, 'Hpiece', 0.0, true),
('Harmony Pró', null, 'HPro', 0.0, true),
('Handpiece Shell MGL', null, 'HPS MGL', 0.0, true),
('HP Sheles', null, 'HPSheles', 0.0, true),
('HP Spot Sensor PCB', null, 'HPSpot', 0.0, true),
('HS-Head piece', null, 'HS', 0.0, true),
('High Voltage Probe', null, 'HVOLTPROB', 0.0, true),
('High Voltage Power Supply', null, 'HVPS', 0.0, true),
('Reparação Fonte Candela Gmax Pro SN: 9914-9035-0125', null, 'HVPS REP', 0.0, true),
('HVPS for power supply', null, 'HVPSpower', 0.0, true),
('Hygienic', null, 'Hygienic', 0.0, true),
('ICON', null, 'ICON', 0.0, true),
('Icool', null, 'Icool', 0.0, true),
('Import Cost', null, 'IMP', 0.0, true),
('Inmode', null, 'Inm', 0.0, true),
('Inox Tanks', null, 'Inox Tanks', 0.0, true),
('Instruments', null, 'INST', 0.0, true),
('Installment', null, 'INSTAL', 0.0, true),
('International Service Fee', null, 'INT_FEE', 0.0, true),
('208-230 V /50/60Hz- 3 kj/s', null, 'Inverter Charger', 0.0, true),
('Iron Part', null, 'IPart', 0.0, true),
('Ao Abrigo do Art. 14 nº1 Alinea a', null, 'Isenta Iva', 0.0, true),
('isento de IVA ao abrigo da alínea a) do número 1 do artigo 14º do CIVA', null, 'Isento Angola', 0.0, true),
('Isenta ao abrigo do Artigo 14 do RITI', null, 'Isento IVA Bens', 0.0, true),
('Isenta ao abrigo da Alinea C do nº5 do Artigo 6º do CIVA', null, 'Isento IVA-Serv', 0.0, true),
('Isolaz', null, 'ISOLAZ', 0.0, true),
('Infrared Thermometer', null, 'ITER', 0.0, true),
('Inverter Charger', null, 'Iv Charger', 0.0, true),
('Start/Stop Key', null, 'Key', 0.0, true),
('Key Set', null, 'Keyset', 0.0, true),
('Laser Head Repair Kit', null, 'KIT_LH', 0.0, true),
('kit screws for laser head MGL', null, 'kits screws', 0.0, true),
('Labor', null, 'Lab', 0.0, true),
('Labels', null, 'LABELS', 0.0, true),
('Laser Head Cynosure', null, 'LAHCY', 0.0, true),
('Lamp', null, 'LAMP', 0.0, true),
('Mini GentleLase Alexandrite', null, 'LASERALEX', 0.0, true),
('Laser Diodo Depil4Beauty', null, 'LASERD', 0.0, true),
('Laser Head', null, 'LASERH', 0.0, true),
('Laser Lamp', null, 'LASERLAMP', 0.0, true),
('Laser Machine', null, 'LaserMac', 0.0, true),
('LCD Screen', null, 'LCD1', 0.0, true),
('Laser CO2+Fraccionado Dermatologia', 'Equipamentos', 'LCO2', 0.0, true),
('Lightsheer Desire', null, 'LDesire', 0.0, true),
('Laser Diode Module', null, 'LDM', 0.0, true),
('Led', null, 'Led', 0.0, true),
('Lentes Focais', null, 'LENFOC', 0.0, true),
('Lens Holder', null, 'LenHol', 0.0, true),
('Lences', null, 'LENS', 0.0, true),
('LENS CAP', null, 'LENS_CAP', 0.0, true),
('Lentes Distais', null, 'LENTDIS', 0.0, true),
('Lente', null, 'Lente', 0.0, true),
('Laser Hair Removal', null, 'LHR', 0.0, true),
('Light guide', null, 'Light', 0.0, true),
('LightSheer ResurFX', null, 'LIGHT RES', 0.0, true),
('Light Blocking Kit', null, 'LIGHTB', 0.0, true),
('Candela Light Blocking Set', null, 'LIGHTBSET', 0.0, true),
('LightSheer Duet', null, 'LIGHTSH', 0.0, true),
('Lightsheer ET', null, 'Lightsheer ET', 0.0, true),
('Lightsheer XC', null, 'LightXC', 0.0, true),
('Livraison', null, 'Liv', 0.0, true),
('Lens Kit', null, 'LKits', 0.0, true),
('Locker', null, 'Locker', 0.0, true),
('LP', null, 'LP', 0.0, true),
('LPG Cellu M6', null, 'LPG', 0.0, true),
('Long Pulsed Yag', null, 'LPY', 0.0, true),
('Laser screen', null, 'LScreen', 0.0, true),
('Lightsheer Desire', null, 'LSDesire', 0.0, true),
('Laser for spare Part Only', null, 'LSPO', 0.0, true),
('Laser Repair', null, 'LSRP', 0.0, true),
('Lutronic Clarity II', null, 'LUTCL', 0.0, true),
('Lumenis - M22', null, 'M22', 0.0, true),
('Lumenis M22', null, 'M22 Lumenis', 0.0, true),
('Machine and Appliances', null, 'MACHAPP', 0.0, true),
('Machine Spares', null, 'MACHSP', 0.0, true),
('Mainfold', null, 'MaiFo', 0.0, true),
('Maintenance', null, 'maint', 0.0, true),
('Maletine', null, 'Mal', 0.0, true),
('Manutenção MGL', null, 'MAN', 0.0, true),
('Aplicador equipamento Apollo', null, 'MANAPOLLO', 0.0, true),
('Mangueira Cryo', null, 'MANG', 0.0, true),
('Manípulo', null, 'MANI', 0.0, true),
('Manutenção', null, 'MANUT', 0.0, true),
('Mão de Obra', null, 'MAO', 0.0, true),
('Maquina', null, 'maq', 0.0, true),
('Máquina Depiladora', null, 'MaqDepil', 0.0, true),
('Material included:', null, 'MAT', 0.0, true),
('Material para desenvolvimento de projeto de estética', null, 'MATPR', 0.0, true),
('Material de Substituição', null, 'MatSub', 0.0, true),
('Memory Card', null, 'MCard', 0.0, true),
('Zero Rated - Medical Use Only', null, 'MD', 0.0, true),
('Mechanical Parts', null, 'MECAPART', 0.0, true),
('Mechanical Appliances', null, 'MECHAN', 0.0, true),
('Medical Material', null, 'Med. material', 0.0, true),
('Medical Equipment', null, 'Medequip', 0.0, true),
('MEG 50', null, 'MEG', 0.0, true),
('Metal', null, 'Metal', 0.0, true),
('Mgl equipment', null, 'MGL', 0.0, true),
('Secret MTR-C1 W/standard accessories', null, 'MICRO NEEDLE RF', 0.0, true),
('Mini Accent', null, 'MiniAccent', 0.0, true),
('Mirror', null, 'Mirr', 0.0, true),
('Motherboard', null, 'Motherboard', 0.0, true),
('MaxG Palomar', null, 'MXPAL', 0.0, true),
('NO CURRENCY MOVEMENTS', null, 'NCM', 0.0, true),
('ND YAG 1064 F non cooled', null, 'NDYAG_F', 0.0, true),
('New Cynosure Ellite Plus', null, 'NEP', 0.0, true),
('NET WEIGHT', null, 'NET', 0.0, true),
('New', null, 'New', 0.0, true),
('New Cynosure Elite Plus ELMD0833ELM+', null, 'New Elite Puls', 0.0, true),
('New Fiber', null, 'NewFI', 0.0, true),
('New HVPS Unit Configured for Candela Mini-GentleLASE', null, 'NEWHVPS', 0.0, true),
('Nordlys', null, 'Nord', 0.0, true),
('Nota de Crédito referente à fatura nº', null, 'NOTA CRE', 0.0, true),
('Nota', null, 'NT', 0.0, true),
('Open Balance', null, 'OB', 0.0, true),
('Óculos', null, 'OCULOS', 0.0, true),
('Open Balance Mini Gentlelase', null, 'OpenBalanceMini', 0.0, true),
('Ophir', null, 'OPHIR', 0.0, true),
('Optic Cap', null, 'OpticCap', 0.0, true),
('ORDER #1', null, 'ORDER', 0.0, true),
('Orings', null, 'ORG', 0.0, true),
('Steel Orings for MGL laser head', null, 'oring', 0.5, true),
('Orings for Laser Head', null, 'ORINGS', 0.0, true),
('Orings for Triple Bore', null, 'ORINGS TRIPL', 0.0, true),
('Orings for Flash Lamp', null, 'OringsFL', 0.0, true),
('OWNERSHIP: All4Laser Unip.Lda', null, 'OWNERS', 0.0, true),
('Pack 20 Lentes', null, 'PACK20', 0.0, true),
('Pack 25 Lentes', null, 'Pack25', 0.0, true),
('Banco BPI - NIB 001000004101165000165   IBAN PT50001000004101165000165  SWIFT/BIC  BBPIPTPL', null, 'PAG EUR', 0.0, true),
('Banco BPI - NIB 001000004101165000165 IBAN PT50001000004101165000165 SWIFT/BIC BBPIPTPL', null, 'Pag Euros', 0.0, true),
('Banco BPI  IBAN-PT50001099994101165060185  SWIFT/BIC-BBPIPTPL  BRANCH NUMBER-2311', null, 'PAG USD', 0.0, true),
('Parafusos', null, 'Parafusos', 0.0, true),
('Payment Terms', null, 'PAYT', 0.0, true),
('Power Cable', null, 'PCable', 0.0, true),
('PCBCART Sample', null, 'PCBCART', 0.0, true),
('power device unit', 'Manutenção e Reparação', 'PDU', 0.0, true),
('Peça de Mão de Laser', null, 'PeçaMão', 0.0, true),
('Pedal', null, 'PED', 0.0, true),
('Pending', null, 'Pend', 0.0, true),
('Pens', null, 'PEns', 0.0, true),
('Per Diem (Meals & Subsistence)', null, 'PERD', 0.0, true),
('Personal', null, 'Pers', 0.0, true),
('Pierde Agua', null, 'PIAgua', 0.0, true),
('Pico Impact', null, 'Pico', 0.0, true),
('Picosure', null, 'PIcosure', 0.0, true),
('Picosure toolkit', null, 'PicosureTool', 0.0, true),
('Picoway', null, 'PicoW', 0.0, true),
('Piezas de Mano', null, 'PieMano', 0.0, true),
('Pixel', null, 'Pixc', 0.0, true),
('Pixel Pro 2940 nm - Erbium Yag 2940nm', null, 'PIXELPR', 0.0, true),
('Pixel Pro 2940nm - Erbium Yag 2940nm Ipixel', null, 'PIXELPRO', 0.0, true),
('Platino', null, 'PLA', 0.0, true),
('Plastic', null, 'Plas', 0.0, true),
('Plastic cover spare parts', null, 'PLASTICC', 0.0, true),
('Plate', null, 'Plate', 0.0, true),
('Plataforma Vibratória', 'Equipamentos', 'PlatVibratoria', 0.0, true),
('Placa', null, 'PLC', 0.0, true),
('Placa Ventoinhas', null, 'PLCVENT', 0.0, true),
('Plunger', null, 'PLUNG', 0.0, true),
('Ponta', null, 'Pon', 0.0, true),
('Ponta de Corte', null, 'PONTCO', 0.0, true),
('Ponteira Facial', null, 'PontFacial', 0.0, true),
('Pre Owned Used Diode Laser for Repair', null, 'PREOWN', 0.0, true),
('Pressoterapia Beauty Services', null, 'PRESBS', 0.0, true),
('Pressure switch', null, 'PressSwitch', 0.0, true),
('Print', null, 'Prin', 0.0, true),
('Probe', null, 'Probe', 0.0, true),
('Gentlelase Pro-U', null, 'ProU', 0.0, false),
('Pistola de Soldadura Laser', null, 'PSol', 0.0, true),
('GentleMAX PRO PLUS Laser System CE with ACC (no handpiece) w/Standard 1-year warranty', null, 'PTO103576', 0.0, true),
('PULSAR', 'Peças', 'Pulsar', 0.0, true),
('Power Courd', null, 'PWCD', 0.0, true),
('Power Supply', null, 'PWSupl', 0.0, true),
('Mini-GentleLASE Quick-Release Fitting for Fluid System Female-Only PVC', null, 'QR_FLUIDS_FEMAL', 0.0, true);
insert into public.tabela_precos (nome, categoria, referencia, preco, ativo) values
('Mini-GentleLASE Quick-Release Fitting for Fluid System Male-Only SS', null, 'QR_FLUIDS_MALE', 0.0, true),
('Quanta Duetto', null, 'QUANTAD', 0.0, true),
('Rack', null, 'Rack', 0.0, true),
('Radiator', null, 'Rad', 0.0, true),
('Recondicionamento', null, 'Recondi', 0.0, true),
('Refurbished HVPS Unit Configured for Candela Mini-GentleLASE', null, 'REF_HVPS', 0.0, true),
('Refurbished', null, 'Refurbished', 0.0, true),
('Refurbished Head', null, 'REFURHEAD', 0.0, true),
('Recondicionamento Cabeza Laser Cynosure', null, 'RefurHeadCyno', 6000.0, true),
('Refurbished Soprano Laser XLI', null, 'REFUSOPR', 0.0, true),
('Relatório', null, 'RelT', 0.0, true),
('Remanescente', null, 'Rem', 0.0, true),
('Remaining Balance', null, 'Rem. Bal', 0.0, true),
('Replacement', null, 'REP', 0.0, true),
('Mini Gentle Laser Head', 'Peças', 'rep 14', 1000.0, true),
('Reparación equipo', null, 'Rep Equipo', 0.0, true),
('Reparação Peça de mão Harmony XL', null, 'REP_HMXLHP_SHR', 0.0, true),
('Hora Deslocação Técnico', 'Manutenção e Reparação', 'REP01', 50.0, true),
('Hora Trabalho Técnico', 'Manutenção e Reparação', 'REP02', 100.0, true),
('Serviço Manutenção Periódica', 'Manutenção e Reparação', 'REP03', 1000.0, true),
('Fonte de Alimentação Mini GLAlex', 'Manutenção e Reparação', 'REP04', 4500.0, true),
('Flashlamp Mini Gentlelase Alex', 'Peças', 'REP05', 600.0, true),
('Condensadores Mini Gentlelase Alex', 'Peças', 'REP06', 1200.0, true),
('Punho Mini GentleYag', 'Manutenção e Reparação', 'REP07', 230.0, true),
('Locker Slider', 'Manutenção e Reparação', 'REP08', 40.0, true),
('Bomba Àgua Ywaki V-Beam', 'Manutenção e Reparação', 'REP09', 501.62, true),
('Bomba de Agua IWAVI', 'Peças', 'REP10', 400.0, true),
('Reparação Grupo Magnetico', 'Manutenção e Reparação', 'REP11', 500.0, true),
('Condesadores Mini Gentle Yag', 'Peças', 'REP12', 3640.0, true),
('H. DRIVE', null, 'REP13', 590.0, true),
('Módulo de Sistema de Orientação', 'Manutenção e Reparação', 'REP14', 2000.0, true),
('Painel frontal completo com touch screen e unidade de delivery system (Mini Gentlelase)', 'Manutenção e Reparação', 'REP15', 3225.0, true),
('Painel direito em aço reforçado - Mini Gentlelase', 'Manutenção e Reparação', 'REP16', 1278.0, true),
('Painel esquerdo em aço reforçado - Mini Gentlelase', 'Manutenção e Reparação', 'REP17', 1278.0, true),
('Painel superior com abertura para sistema de criogénio - Mini Gentlelase', null, 'REP18', 1945.0, true),
('Painel para sistema de água em aço reforçado - Mini Gentlelase', 'Manutenção e Reparação', 'REP19', 1680.0, true),
('Painel direito em aço reforçado com suporte para fibra e delivery system - Mini Gentlelase', 'Manutenção e Reparação', 'REP20', 2125.0, true),
('HVPS - Fonte de Alimentação Mini GLYag', 'Manutenção e Reparação', 'REP21', 7200.0, true),
('Delivery System 12/15/18 para Mini GYag', 'Manutenção e Reparação', 'REP22', 2250.0, true),
('Fonte de Alimentação Ultrashape V2', null, 'REP23', 9000.0, true),
('Servidor de Alto Desempenho Ultrashape V2', null, 'REP24', 18000.0, true),
('PDU Ultrashape V2', null, 'REP25', 8500.0, true),
('Sistema de Refrigeração Ultrashape V2', null, 'REP26', 4500.0, true),
('Módulo de Ultrassom', null, 'REP27', 10824.0, true),
('HVPS Power Supply for Repair', null, 'REP28', 60.0, true),
('Laser Head for MGL for Repair', null, 'REP29', 0.0, true),
('Fibra Gentlelase 12/15/18mm', null, 'REP30', 896.0, true),
('Reparação Laser', null, 'REP31', 0.0, true),
('Válvula criogénio Mini Gentlelase', null, 'REP32', 420.0, true),
('Micro Switch Peça de Mão MGL', null, 'REP33', 95.0, true),
('Di Water Cart', null, 'REP34', 0.0, true),
('Repair', null, 'REPA', 0.0, true),
('Repair Service of HVPS for Mini GentleLAse and Mini GentleYAg', null, 'REPAIR_HVPS', 0.0, true),
('Reparacion', null, 'REPAR', 0.0, true),
('Reparação CPU', null, 'REPARCPU', 0.0, true),
('Repaired Handpiece', null, 'REPHP', 0.0, true),
('Reparação de Laser', null, 'REPLASER', 0.0, true),
('Reparação Ultrashape', null, 'REPUS', 0.0, true),
('GentleLASE/GentleLASE-Plus DI Fluid Reservoir Assembly with Tank', null, 'RESERV', 0.0, true),
('MGL/Y DI Water Reservoir Fitting - T fitting', null, 'RESERV_FITT', 0.0, true),
('Resistência', null, 'Resi', 0.0, true),
('Resistencia de Agua MGL', null, 'ResistAguar', 0.0, true),
('Retoma', null, 'Ret', 0.0, true),
('Revisão', null, 'Revi', 0.0, true),
('Revlite', null, 'RevLite', 0.0, true),
('RF amplifier', null, 'RFAMPL', 0.0, true),
('RF Laser', null, 'RFL', 0.0, true),
('Refurbished laser handpiece', null, 'RHP', 0.0, true),
('Rubber Kit', null, 'RKIT', 0.0, true),
('ROD', null, 'ROD', 0.0, true),
('Rod to Refurbished', null, 'RODREF', 0.0, true),
('Repuesto PC', null, 'RPC', 0.0, true),
('Parceria Formatk Manipulo R-SONIC', null, 'RSONIC', 0.75, true),
('Rental Candela Gmax Pro', null, 'RT', 0.0, true),
('Rental Gmax Pro Plus', null, 'RT_GMPP', 0.0, true),
('Sample', null, 'SAMPLE', 0.0, true),
('Sistema de Criogénio', null, 'SC01', 0.0, true),
('Sistema de Controle', null, 'SC02', 0.0, true),
('Scissor', null, 'Scissor', 0.0, true),
('Screw Kit', null, 'ScKit', 0.0, true),
('Signal Connector', null, 'SConnector', 0.0, true),
('Screen', null, 'Screen', 0.0, true),
('Candela Screw Kits', null, 'SCREWK', 0.0, true),
('Second', null, 'Sec', 0.0, true),
('Sensor de Fluxo', null, 'SenFLu', 0.0, true),
('Sensor', null, 'Sensor', 0.0, true),
('Serial Number:', null, 'SERIALN', 0.0, true),
('Serviço técnico', null, 'SERTEC', 0.0, true),
('Service Description', null, 'SERVD', 0.0, true),
('Contrato Manutenção', 'Manutenção e Reparação', 'Serviços', 8000.0, true),
('Services Rendering', null, 'ServRend', 0.0, true),
('Set Candela Gentle yag', null, 'SETCGENT', 0.0, true),
('Plastic and Steal Shell', null, 'SHELL', 0.0, true),
('Ai Shield', null, 'Shield', 0.0, true),
('Shipping', null, 'Ship', 0.0, true),
('`` MedTechPlus`` Soyuza Pechatnikov str., 25 A, Office space 4 H, room 1 Saint-Petersburg, Russia, 190121', null, 'Shiping To :', 0.0, true),
('Shipping Costs', null, 'SHPCOST', 0.0, true),
('SHR', null, 'SHR', 0.0, true),
('SHR Pro 5 - In motion AFT/Tecnologia NIR', null, 'SHRPRO5', 0.0, true),
('Shr Pro 6.4', null, 'SHRPRO64', 0.0, true),
('Shutter', null, 'SHUT', 0.0, true),
('SI Handpiece', null, 'SIHP', 0.0, true),
('Sitcon', null, 'Sitc', 0.0, true),
('Slider Lens', null, 'SLI_LENS', 0.0, true),
('MGL Slider Buttons', null, 'SLIDER_BUTTONS', 0.0, true),
('Slider Cap', null, 'SLIDER_CAP', 0.0, true),
('Smartxide', null, 'SMARX', 0.0, true),
('Serviço de Manutenção C/ Revisão da Cabeça', null, 'SMP_WH', 0.0, true),
('Soprano', null, 'SOP', 0.0, true),
('Soprano laser for refurbishing', null, 'SOP_REF', 0.0, true),
('Sensor de Fluxo Soprano', null, 'SOP_SENSFL', 0.0, true),
('Soprano Handpiece', null, 'SOPHP', 0.0, true),
('Soprano Ice', null, 'SOPI', 0.0, true),
('Soprano Platinum', null, 'SOPPLAT', 0.0, true),
('Soprano Pontiaco/Pro', null, 'SOPPP', 0.0, true),
('Soprano + Peça de mão e acessórios', null, 'Soprano', 0.0, true),
('Soprano Titanium', null, 'SOPTIT', 0.0, true),
('Soprano XL', null, 'SOPXL', 0.0, true),
('Soprano XLI', null, 'SOPXLI', 0.0, true),
('Spare', null, 'Spar', 0.0, true),
('Capacitor Charger', null, 'Spare  Parts', 0.0, true),
('Spare part for aesthetic equipment', null, 'Spare Part', 30.81, true),
('Fiber Optic, Shells, Foot Pedal, Holder', null, 'Spare Parts', 0.0, true),
('Spare part for Laser', null, 'SpareLaser', 0.0, true),
('Control Panel Parts', null, 'SpareParts', 0.0, true),
('Support Arm', null, 'SPARM', 0.0, true),
('Spare Part', null, 'SPart', 0.0, true),
('Spa SHR ALMA LASERS', null, 'SPASHR', 0.0, true),
('Spectra', null, 'Spectra', 0.0, true),
('Spots', null, 'SPOTS', 50.0, true),
('Spare part  for wood machine', null, 'SPWM', 0.0, true),
('SQ20 Cart', null, 'SQ20', 0.0, true),
('SQ22 Cart', null, 'SQ22', 0.0, true),
('SR Pro - Light tech 570-950 nm', null, 'SRPRO', 0.0, true),
('Parceria Formatk Manipulo ST', null, 'ST', 0.7, true),
('Stack', null, 'Stack', 0.0, true),
('Red Stand', null, 'Stand', 0.0, true),
('Staplers', null, 'Stap', 0.0, true),
('Sticker', null, 'STI', 0.0, true),
('Substituição', null, 'Subs', 0.0, true),
('Suporte', null, 'Sup', 0.0, true),
('Support piece', null, 'SUPie', 0.0, true),
('Solenoid Valve', null, 'SV', 0.0, true),
('Switch', null, 'Switch', 0.0, true),
('System Cable', null, 'SYSC', 0.0, true),
('Transporte Fee', null, 'Taxa', 0.0, true),
('Bomba de água MGL - Topo', null, 'TBOMB', 0.0, true),
('Technical Training - Module I: Introduction to the repairing of medical lasers', null, 'TEC_TR1', 0.0, true),
('Technical Training - Module X: Shutter Calibration', null, 'TEC_TR10', 0.0, true),
('Technical Training - Module II: Water system repair (Pump Iwoka)', null, 'TEC_TR2', 0.0, true),
('Technical Training - Module III: repairing of model HVPS 24V', null, 'TEC_TR3', 0.0, true),
('Technical Training - Module IV: repairing of model  HVPS 2000U', null, 'TEC_TR4', 0.0, true),
('Technical Training - Module V: Capacitator repair module', null, 'TEC_TR5', 0.0, true),
('Technical Training - Module VI: Coil repairing module', null, 'TEC_TR6', 0.0, true),
('Technical Training - Module VII: Distribution Board', null, 'TEC_TR7', 0.0, true),
('Technical Training - Module VIII: Laser Head Calibration', null, 'TEC_TR8', 0.0, true),
('Technical Training - Module IX: Laser Head Refurbishment', null, 'TEC_TR9', 0.0, true),
('Technical Service', null, 'Techserv', 0.0, true),
('Testing', null, 'Test', 0.0, true),
('Thermage', null, 'Therma', 0.0, true),
('Thermolift RED', null, 'Thermolift', 0.0, true),
('Tip', null, 'TIP', 0.0, true),
('Tips Cynosure', null, 'TIPSCYN', 0.0, true),
('Tool Kit Cynosure', null, 'TKC', 0.0, true),
('Turning Mirror', null, 'TMirror', 0.0, true),
('Travel', null, 'Tra', 0.0, true),
('Travel & Accommodation Expenses', null, 'TRA_EXP', 0.0, true),
('Trade in', null, 'Trad', 0.0, true),
('Training', null, 'Train', 0.0, true),
('specialized training', null, 'training', 0.0, true),
('Transporte', null, 'Trans', 0.0, true),
('Transmission Line Alex', null, 'TransLine', 0.0, true),
('Transporte Equipamentos Carfatrans', null, 'TRANSP', 0.0, true),
('Tratamento Ultrashape', null, 'Tratamento Ultr', 0.0, true),
('Tratamento Apollo', null, 'TratApollo', 0.0, true),
('Training and Installation', null, 'TRG', 0.0, true),
('Triple Bore', null, 'TRIB', 0.0, true),
('Trip', null, 'Trp', 0.0, true),
('Taxa de Urgência', null, 'TX URG', 0.0, true),
('Used Display', null, 'udisplay', 0.0, true),
('Ulthera', null, 'Ult', 0.0, true),
('Ultra Accent', null, 'Ultra_Accent', 0.0, true),
('ULTRASHAPE V3 RF HANDPIECE', null, 'ULTRA_HPRF', 0.0, true),
('ULTRASHAPE V3 TRANSDUCER WITH VDF', null, 'ULTRA_TRANSD', 0.0, true),
('UltraPulse', null, 'UltraP', 0.0, true),
('Umbilical', null, 'Umb', 0.0, true),
('Upgrade', null, 'Upgr', 0.0, true),
('Upgrade Spot 18mm', 'Manutenção e Reparação', 'UPGRAD', 416.7, true),
('USB Pens', null, 'USB', 0.0, true),
('UltraShape Damaged Transducers', null, 'USDAM', 0.0, true),
('Used', null, 'Used', 0.0, true),
('Used GentleLase Mini Cosmetic Laser (made in USA)', null, 'used_mgl', 0.0, true),
('2ª tranche do transdutor + 50% do manipulo + voo', null, 'USERF', 0.0, true),
('3ª tranche do transdutor+ 50% do manipulo', null, 'USERF1', 0.0, true),
('User Manual', null, 'USManual', 0.0, true),
('UltraShape Used Transducer', null, 'USUSED', 0.0, true),
('Ultrashape V3', null, 'USV3', 0.0, true),
('Unilarge Thermometer Handpiece', null, 'UTH', 0.0, true),
('Valves', null, 'Valv', 0.0, true),
('Valves C', null, 'ValvC', 1425.0, true),
('Vanquish', null, 'Vanq', 0.0, true),
('Vbeam Perfecta Laser', null, 'VBeam', 0.0, true),
('Vectus', null, 'Vectus', 0.0, true),
('Velcro', null, 'Vel', 0.0, true),
('Velashape', null, 'Vela', 0.0, true),
('Velashape III', null, 'VelaShp3', 0.0, true),
('Venda', null, 'Venda', 0.0, true),
('Ventana', null, 'Vent', 0.0, true),
('Ventilador Zimmer', null, 'VENTZIMMER', 0.0, true),
('Valor do Frete', null, 'VFrete', 0.0, true),
('VIC', null, 'Vicor', 0.0, true),
('Venus', null, 'Vn', 0.0, true),
('Voos', null, 'VOO', 0.0, true),
('VP Cooled - AFT', null, 'VPCOOLED', 0.0, true),
('Vbeam Perfecta Laser', 'Equipamentos', 'VPL', 0.0, false),
('Water pump Shell Kit', null, 'Water_PUMP', 0.0, true),
('Water Resistance', null, 'Water_RES', 0.0, true),
('Water Bomb', null, 'WaterB', 0.0, true),
('Water Heater', null, 'WaterHeat', 0.0, true),
('Water Pump', null, 'WaterPump', 0.0, true),
('Water Tank', null, 'WaterT', 0.0, true),
('Water Filter', null, 'WatFilter', 0.0, true),
('Water Hoses KIt', null, 'WATHOSES', 0.0, true),
('WEIGHT', null, 'WEIGHT', 0.0, true),
('Water Filters', null, 'WFILTERS', 0.0, true),
('Water Hose Connector', null, 'WHconcector', 0.0, true),
('Windows', null, 'Wind', 0.0, true),
('Window Glass for distance gauge', null, 'Windowglass', 0.0, true),
('Wires', null, 'Wir', 0.0, true),
('Water Module System', null, 'WMS', 0.0, true),
('Water Radiator', null, 'WRadiator', 0.0, true),
('Warranty:', null, 'WRT', 0.0, true),
('Water Flow Sensor', null, 'WTflowS', 0.0, true),
('Yag', null, 'Yag', 0.0, true),
('GentleYag Pro', null, 'Yagpro', 0.0, true),
('Coolsculpting', null, 'Zelt', 0.0, true),
('ZELTIQ', null, 'Zeltiq', 0.0, true),
('1 Ano de Garantia', null, '1Gar', 0.0, true),
('Case', null, '3D Printer Part', 0.0, true),
('Water Pump, Power Supply, Hitter capacitor', null, '3Dprinterpart', 0.0, true),
('6 Meses de Garantia', null, '6Gar', 0.0, true),
('Stand de Exposição', null, '100', 0.0, true),
('Canister HFC-134a /1000g, ALUM', null, '1600-00-0219', 0.0, true),
('Piezosurgery plus', null, '05170003', 0.0, true),
('Used mini gentleyag cosmetic laser', null, '8543709990', 0.0, true);
